# (c) Copyright 2016 Hewlett Packard Enterprise Development LP
# (c) Copyright 2017 SUSE LLC
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---

- name: ardana-hypervisor-monitoring | configure | create conf dirs
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ ahv_conf_dir }}"
    - "{{ ahv_monitor.conf_dir }}"

- name: ardana-hypervisor-monitoring | configure | generate per-vm confs
  become: yes
  template:
    src: monitor_vm.json.j2
    dest: "{{ ahv_monitor.conf_dir }}/{{ item.vm }}.json"
    mode: 0644
    owner: root
    group: root
  with_items: ahv_monitor.vms
